#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

# add our commands
$application->add(new Serve());
$application->add(new MakeController());
$application->add(new MakeModel());

$application->run();